server:
  port: 8080

ftp:
  host: 47.103.53.243 #部署到服务器后用 localhost  本地47.103.53.243
  port: 21
  username: ftpuser
  password: 111111
  basePath: /home/ftpuser/www/images
  imagBaseUrl: http://image.franxx.top/images
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  spring:
    datasource:
      base:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
#        username: root
#        password: 111111
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true

    servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 10MB

    mybatis:
      config-location: classpath:mybatis-cfg.xml
      mapper-locations: classpath:top/franxx/blog/mapper/*.xml


